# Generated by Django 5.2.10 on 2026-08-04 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('general', 'General'), ('attraction', 'Tourist Attraction'), ('charging', 'EV Charging Station')], default='general', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EVChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_type', models.CharField(choices=[('type1', 'Type 1 (J1772)'), ('type2', 'Type 2 (Mennekes)'), ('ccs', 'CCS (Combined Charging System)'), ('chademo', 'CHAdeMO'), ('tesla', 'Tesla Supercharger'), ('universal', 'Universal')], max_length=20)),
                ('power_level', models.CharField(choices=[('level1', 'Level 1 (120V)'), ('level2', 'Level 2 (240V)'), ('dcfast', 'DC Fast Charging')], max_length=20)),
                ('number_of_ports', models.PositiveIntegerField(default=1)),
                ('charging_speed', models.CharField(max_length=50)),
                ('is_operational', models.BooleanField(default=True)),
                ('cost_per_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('available_24_7', models.BooleanField(default=False)),
                ('requires_membership', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charging_station', to='maps.location')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_distance', models.FloatField()),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('path_coordinates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='maps.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='maps.location')),
            ],
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('historical', 'Historical Site'), ('natural', 'Natural Wonder'), ('museum', 'Museum'), ('religious', 'Religious Site'), ('entertainment', 'Entertainment'), ('adventure', 'Adventure Activity'), ('cultural', 'Cultural Site'), ('beach', 'Beach'), ('park', 'Park/Garden'), ('viewpoint', 'Viewpoint'), ('other', 'Other')], max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_attraction', to='maps.location')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField(help_text='Order of this waypoint in the route (1, 2, 3, ...)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='maps.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
